### PR TITLE
add formula and patch for psync

### PR DESCRIPTION
**Pull request by agawande**

### CODE REVIEW

**Comment by agawande** [comment]
@cawka

**Comment by cawka** [comment]
It's failing with boost detection on aarch64 platform. You need to hack in wscript to explicilty add more boost libraries.

```
['/tmp/ndk-cawka/target/psync/arm64-v8a/build/c++', '-L/opt/android/ndk-bundle/packages/openssl/1.1.1-pre8/libs/arm64-v8a', '-L/opt/android/ndk-bundle/packages/sqlite/3.18.0/libs/arm64-v8a', '-lcrypto', '-lssl', '-lsqlite3', '-llog', 'test.cpp.1.o', '-o/private/tmp/ndk-cawka/target/psync/arm64-v8a/build/build/.conf_check_da247eed7d26c3e8a1f5ea02192f7d1b/testbuild/testprog', '-Wl,-Bstatic', '-L/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm', '-Wl,-Bdynamic', '-L/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm', '-lboost_system', '-lboost_thread', '-lboost_log', '-lboost_log_setup', '-lboost_iostreams', '-no-canonical-prefixes', '-Wl,--build-id', '-nostdlib++', '-Wl,--no-undefined', '-Wl,-z,noexecstack', '-Wl,-z,relro', '-Wl,-z,now', '-Wl,--warn-shared-textrel', '-Wl,--fatal-warnings', '-lgcc', '-Wl,--exclude-libs,libgcc.a', '-latomic', '-Wl,--exclude-libs,libatomic.a']
err: /opt/android/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libboost_atomic.so, needed by /opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so, not found (try using -rpath or -rpath-link)
/opt/android/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libboost_chrono.so, needed by /opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so, not found (try using -rpath or -rpath-link)
/opt/android/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libboost_date_time.so, needed by /opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so, not found (try using -rpath or -rpath-link)
/opt/android/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libboost_filesystem.so, needed by /opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so, not found (try using -rpath or -rpath-link)
/opt/android/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libboost_regex.so, needed by /opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so, not found (try using -rpath or -rpath-link)
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::absolute(boost::filesystem::path const&, boost::filesystem::path const&)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::basic_regex<wchar_t, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::do_assign(wchar_t const*, wchar_t const*, unsigned int)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::re_detail_106800::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::re_detail_106800::put_mem_block(void*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::re_detail_106800::get_mem_block()'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::match_results<wchar_t const*, std::__ndk1::allocator<boost::sub_match<wchar_t const*> > >::maybe_assign(boost::match_results<wchar_t const*, std::__ndk1::allocator<boost::sub_match<wchar_t const*> > > const&)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::detail::copy_option, boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::directory_iterator_construct(boost::filesystem::directory_iterator&, boost::filesystem::path const&, boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::rename(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::re_detail_106800::get_default_error_string(boost::regex_constants::error_type)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::path::operator/=(boost::filesystem::path const&)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::dir_itr_close(void*&, void*&)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::re_detail_106800::verify_options(unsigned int, boost::regex_constants::_match_flags)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::path::parent_path() const'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::match_results<char const*, std::__ndk1::allocator<boost::sub_match<char const*> > >::maybe_assign(boost::match_results<char const*, std::__ndk1::allocator<boost::sub_match<char const*> > > const&)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::remove(boost::filesystem::path const&, boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::path::filename() const'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::re_detail_106800::is_combining_implementation(unsigned short)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::file_size(boost::filesystem::path const&, boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::current_path(boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::re_detail_106800::perl_matcher<char const*, std::__ndk1::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::re_detail_106800::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::system_complete(boost::filesystem::path const&, boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::directory_iterator_increment(boost::filesystem::directory_iterator&, boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::re_detail_106800::raise_runtime_error(std::runtime_error const&)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::filesystem::path_traits::convert(wchar_t const*, wchar_t const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >&, std::__ndk1::codecvt<wchar_t, char, mbstate_t> const&)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::read_symlink(boost::filesystem::path const&, boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >&)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::re_detail_106800::perl_matcher<wchar_t const*, std::__ndk1::allocator<boost::sub_match<wchar_t const*> >, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > >::construct_init(boost::basic_regex<wchar_t, boost::regex_traits<wchar_t, boost::cpp_regex_traits<wchar_t> > > const&, boost::regex_constants::_match_flags)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::re_detail_106800::cpp_regex_traits_implementation<wchar_t>::transform_primary(wchar_t const*, wchar_t const*) const'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::space(boost::filesystem::path const&, boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::last_write_time(boost::filesystem::path const&, boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::re_detail_106800::cpp_regex_traits_implementation<wchar_t>::transform(wchar_t const*, wchar_t const*) const'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::do_assign(char const*, char const*, unsigned int)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log_setup.so: undefined reference to `boost::filesystem::path::codecvt()'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
/opt/android/ndk-bundle/packages/boost/1.68.0/libs/arm64-v8a/llvm/libboost_log.so: undefined reference to `boost::filesystem::detail::equivalent(boost::filesystem::path const&, boost::filesystem::path const&, boost::system::error_code*)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

from /private/tmp/ndk-cawka/target/psync/arm64-v8a/build: Test does not build: Traceback (most recent call last):
  File "/private/tmp/ndk-cawka/target/psync/arm64-v8a/build/.waf-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Configure.py", line 325, in run_build
    bld.compile()
  File "/private/tmp/ndk-cawka/target/psync/arm64-v8a/build/.waf-2.0.14-e67604cd8962dbdaf7c93e0d7470ef5b/waflib/Build.py", line 176, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed with exit status 1 (run with -v to display more information)

from /private/tmp/ndk-cawka/target/psync/arm64-v8a/build: The configuration failed
Could not link against boost libraries using supplied options
from /private/tmp/ndk-cawka/target/psync/arm64-v8a/build: The configuration failed
```

**Comment by agawande** [comment]
Not sure why it builds for me as it (environment is Ubuntu 18.04 LTS, ndk is r19b: 19.1.5304403):

```
= building for architecture: arm64
  building for abi: arm64-v8a
    using C++ standard library: llvm
{"LC_MESSAGES"=>"C", "CC"=>"/tmp/ndk-ashlesh/target/psync/arm64-v8a/build/cc", "CPP"=>"/tmp/ndk-ashlesh/target/psync/arm64-v8a/build/cc  -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes  -fpic  -O0 -UNDEBUG -fno-limit-debug-info  -g -fexceptions -frtti -DANDROID -D__ANDROID_API__=23  -Wa,--noexecstack -Wformat -Werror=format-security  -E", "AR"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar", "NM"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm", "AS"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as", "LD"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld", "RANLIB"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-ranlib", "READELF"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-readelf", "STRIP"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip", "CFLAGS"=>" -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes  -fpic  -O0 -UNDEBUG -fno-limit-debug-info  -g -fexceptions -frtti -DANDROID -D__ANDROID_API__=23  -Wa,--noexecstack -Wformat -Werror=format-security ", "LDFLAGS"=>"   -no-canonical-prefixes -Wl,--build-id -nostdlib++ -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings  -lgcc -Wl,--exclude-libs,libgcc.a -latomic -Wl,--exclude-libs,libatomic.a ", "CXX"=>"/tmp/ndk-ashlesh/target/psync/arm64-v8a/build/c++", "CXXCPP"=>"/tmp/ndk-ashlesh/target/psync/arm64-v8a/build/c++ -I/home/ashlesh/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -I/home/ashlesh/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -E", "CXXFLAGS"=>" -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes  -fpic  -O0 -UNDEBUG -fno-limit-debug-info  -g -fexceptions -frtti -DANDROID -D__ANDROID_API__=23  -Wa,--noexecstack -Wformat -Werror=format-security "}
      configuring PSync
      building PSync
= building for architecture: x86_64
  building for abi: x86_64
    using C++ standard library: llvm
{"LC_MESSAGES"=>"C", "CC"=>"/tmp/ndk-ashlesh/target/psync/x86_64/build/cc", "CPP"=>"/tmp/ndk-ashlesh/target/psync/x86_64/build/cc  -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes  -fPIC  -O0 -UNDEBUG -fno-limit-debug-info  -g -fexceptions -frtti -DANDROID -D__ANDROID_API__=23  -Wa,--noexecstack -Wformat -Werror=format-security  -E", "AR"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar", "NM"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm", "AS"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-as", "LD"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin/x86_64-linux-android-ld", "RANLIB"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin/x86_64-linux-android-ranlib", "READELF"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin/x86_64-linux-android-readelf", "STRIP"=>"/home/ashlesh/Android/Sdk/ndk-bundle/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin/x86_64-linux-android-strip", "CFLAGS"=>" -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes  -fPIC  -O0 -UNDEBUG -fno-limit-debug-info  -g -fexceptions -frtti -DANDROID -D__ANDROID_API__=23  -Wa,--noexecstack -Wformat -Werror=format-security ", "LDFLAGS"=>"   -no-canonical-prefixes -Wl,--build-id -nostdlib++ -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings  -lgcc -Wl,--exclude-libs,libgcc.a -latomic -Wl,--exclude-libs,libatomic.a ", "CXX"=>"/tmp/ndk-ashlesh/target/psync/x86_64/build/c++", "CXXCPP"=>"/tmp/ndk-ashlesh/target/psync/x86_64/build/c++ -I/home/ashlesh/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -I/home/ashlesh/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -E", "CXXFLAGS"=>" -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes  -fPIC  -O0 -UNDEBUG -fno-limit-debug-info  -g -fexceptions -frtti -DANDROID -D__ANDROID_API__=23  -Wa,--noexecstack -Wformat -Werror=format-security "}
      configuring PSync
      building PSync
= executing post build step: OK
Creating archive file /home/ashlesh/.caches/crew/packages/psync-0.1.0_1.tar.xz
Unpacking archive into /home/ashlesh/Android/Sdk/ndk-bundle/packages/psync/0.1.0
```

**Comment by cawka** [comment]
Merged as part of 0d8d9acd27745da640fc6d3363a8febf51eb8aac, c8bcbad119ac86ab242f41bd4dd3e26566f5104c, and 62e28b0f9424cd35672f774d429d8c5a0b291a57

**Pull request closed without merging**
